// Basic wrapper that maps document types to AI actions and handles provider logic.
import { DOCUMENT_TYPES } from '../../config/documents';
import { AI_ACTION_TYPES } from '../../config/ai';

class ProviderRegistry {
  getActionTypeForDocument(documentType) {
    switch (documentType) {
      case DOCUMENT_TYPES.COVER_LETTER: return AI_ACTION_TYPES.GENERATE_COVER_LETTER;
      case DOCUMENT_TYPES.APPLICATION_EMAIL: return AI_ACTION_TYPES.GENERATE_APPLICATION_EMAIL;
      case DOCUMENT_TYPES.FOLLOW_UP: return AI_ACTION_TYPES.GENERATE_FOLLOW_UP;
      case DOCUMENT_TYPES.THANK_YOU: return AI_ACTION_TYPES.GENERATE_THANK_YOU;
      case DOCUMENT_TYPES.SALARY_NEGOTIATION: return AI_ACTION_TYPES.GENERATE_SALARY_NEGOTIATION;
      case DOCUMENT_TYPES.OFFER_ACCEPTANCE: return AI_ACTION_TYPES.GENERATE_OFFER_ACCEPTANCE;
      case DOCUMENT_TYPES.RESIGNATION: return AI_ACTION_TYPES.GENERATE_RESIGNATION;
      case DOCUMENT_TYPES.REFERENCE_REQUEST: return AI_ACTION_TYPES.GENERATE_REFERENCE_REQUEST;
      case DOCUMENT_TYPES.RECOMMENDATION_REQUEST: return AI_ACTION_TYPES.GENERATE_RECOMMENDATION_REQUEST;
      case DOCUMENT_TYPES.NETWORKING: return AI_ACTION_TYPES.GENERATE_NETWORKING;
      case DOCUMENT_TYPES.LINKEDIN_MESSAGE: return AI_ACTION_TYPES.GENERATE_LINKEDIN_MESSAGE;
      case DOCUMENT_TYPES.INTERNSHIP_REQUEST: return AI_ACTION_TYPES.GENERATE_INTERNSHIP_REQUEST;
      case DOCUMENT_TYPES.SCHOLARSHIP: return AI_ACTION_TYPES.GENERATE_SCHOLARSHIP;
      case DOCUMENT_TYPES.STATEMENT_OF_PURPOSE: return AI_ACTION_TYPES.GENERATE_STATEMENT_OF_PURPOSE;
      default: return AI_ACTION_TYPES.GENERIC_CHAT;
    }
  }
}

export default new ProviderRegistry();
