export const CAREER_CONFIG = {
  WEIGHTS: {
    RESUME_QUALITY: 20,
    ATS_SCORE: 20,
    JOB_MATCH: 20,
    INTERVIEW_SCORE: 15,
    SKILLS: 10,
    CERTIFICATIONS: 5,
    LEARNING_PROGRESS: 5,
    CAREER_COMPLETENESS: 5
  },
  RECOMMENDATION_PRIORITIES: {
    CRITICAL: 'High',
    HIGH: 'High',
    MEDIUM: 'Medium',
    LOW: 'Low'
  },
  DEFAULT_GOAL_STATUS: 'ACTIVE',
  LEARNING_STATUS: {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED'
  }
};

export default CAREER_CONFIG;
