export const DOCUMENT_TYPES = {
  COVER_LETTER: 'COVER_LETTER',
  APPLICATION_EMAIL: 'APPLICATION_EMAIL',
  FOLLOW_UP: 'FOLLOW_UP',
  THANK_YOU: 'THANK_YOU',
  SALARY_NEGOTIATION: 'SALARY_NEGOTIATION',
  OFFER_ACCEPTANCE: 'OFFER_ACCEPTANCE',
  RESIGNATION: 'RESIGNATION',
  REFERENCE_REQUEST: 'REFERENCE_REQUEST',
  RECOMMENDATION_REQUEST: 'RECOMMENDATION_REQUEST',
  NETWORKING: 'NETWORKING',
  LINKEDIN_MESSAGE: 'LINKEDIN_MESSAGE',
  INTERNSHIP_REQUEST: 'INTERNSHIP_REQUEST',
  SCHOLARSHIP: 'SCHOLARSHIP',
  STATEMENT_OF_PURPOSE: 'STATEMENT_OF_PURPOSE',
};

export const DOCUMENT_STATUS = {
  DRAFT: 'DRAFT',
  GENERATED: 'GENERATED',
  EDITED: 'EDITED',
  EXPORTED: 'EXPORTED',
  ARCHIVED: 'ARCHIVED',
};

export const DOCUMENT_HISTORY_ACTIONS = {
  GENERATED: 'Generated',
  EDITED: 'Edited',
  REGENERATED: 'Regenerated',
  AI_IMPROVED: 'AI Improved',
  EXPORTED: 'Exported',
  DELETED: 'Deleted',
};
