export const ROUTES = {
  WELCOME: 'WELCOME',
  MAIN_TABS: 'MAIN_TABS',
  HOME: 'HOME',
  RESUME: 'RESUME', // Used as base route for stack
  RESUME_DASHBOARD: 'RESUME_DASHBOARD',
  RESUME_EDITOR: 'RESUME_EDITOR',
  SECTION_EDITOR: 'SECTION_EDITOR',
  RESUME_PREVIEW: 'RESUME_PREVIEW',
  AI_ASSISTANT: 'AI_ASSISTANT',
  AI_CONVERSATION: 'AI_CONVERSATION',
  TEMPLATES: 'TEMPLATES',
  SETTINGS: 'SETTINGS',
  ATS_SCORE: 'ATS_SCORE',
  COVER_LETTER: 'COVER_LETTER',
  INTERVIEW_PREP: 'INTERVIEW_PREP',
};
