export const ROUTES = {
  WELCOME: 'WELCOME',
  MAIN_TABS: 'MAIN_TABS',
  HOME: 'HOME',
  RESUME: 'RESUME',
  AI_ASSISTANT: 'AI_ASSISTANT',
  TEMPLATES: 'TEMPLATES',
  SETTINGS: 'SETTINGS',
  ATS_SCORE: 'ATS_SCORE',
  COVER_LETTER: 'COVER_LETTER',
  INTERVIEW_PREP: 'INTERVIEW_PREP',
};
